spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ddl
    user: ${db_user}
    password: ${db_pass}
    liquibase-schema: plants
  datasource:

    url: ${db_url}
    hikari:
      schema: plants
    username: ${db_user}
    password: ${db_pass}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: plant
        #        show_sql: true
        format_sql: true
        event:
          merge:
            entity_copy_observer: allow

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${security.github.id}
            clientSecret: ${ security.github.secret }
          google:
            client-id: ${security.google.id}
            client-secret: ${security.google.id}
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
  org:
    springframework:
      security: DEBUG

  com: TRACE